root_app:
  deployment:
    replicas: 1
    image:
      name: linnovate/root
      tag: 2.0.4
    resources: {}
  service:
    default:
      name: "3000"
      port: 3000
      targetPort: 3000
  ingress:
    prefix: 'root'
  persistence: "local"    

root_db:
  deployment:
    replicas: 1
    image:
      name: mongo
      tag: 3.6.3
    resources: {}
  service:
    default:
      name: "headless"
      port: 55555
      targetPort: 0
  persistence: "local"

root_elastic:
  deployment:
    replicas: 1
    image:
      name: elasticsearch
      tag: 5.6.9
    resources: 
      limits:
        memory: 356M # we set this to 100M more than the java memory setting below
    environment:
      es_java_opts: "-Xms256m -Xmx256m"
  service:
    default:
      name: "headless"
      port: 55555
      targetPort: 0
      
global:
  ingress:
    wildcard: 'projects.linnovate.net'
  image: 
    registry: 'docker.io'

# resources: 
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
