apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.4.0 (c7964e7)
  creationTimestamp: null
  labels:
    io.kompose.service: root-graphql
  name: root-graphql
spec:
  replicas: {{ .Values.root_graphql.deployment.replicas }}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: root-graphql
    spec:
      containers:
      - env:
        - name: PORT
          valueFrom:
            configMapKeyRef:
              key: PORT
              name: root-graphql-env
        - name: ROOT_HOST
          valueFrom:
            configMapKeyRef:
              key: ROOT_HOST
              name: root-graphql-env
        - name: ROOT_PORT
          valueFrom:
            configMapKeyRef:
              key: ROOT_PORT
              name: root-graphql-env
        image: "{{ .Values.global.image.registry }}/{{ .Values.root_graphql.deployment.image.name }}:{{ .Values.root_graphql.deployment.image.tag }}"
        name: root-graphql
        ports:
        - containerPort: {{ .Values.root_graphql.service.default.targetPort }}
        resources: {}
      restartPolicy: Always
status: {}
