apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: "root-graphql-env"
data:
  PORT: "{{ .Values.root_graphql.service.default.targetPort }}"
  ROOT_HOST: "http://root-app"
  ROOT_PORT: "{{ .Values.root.root_app.port }}"
