apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.4.0 (c7964e7)
  creationTimestamp: null
  labels:
    io.kompose.service: root-graphql
  name: root-graphql
spec:
  type: ClusterIP
  ports:
  - name: "{{ .Values.root_graphql.service.default.name }}"
    port: {{ .Values.root_graphql.service.default.port }}  
    targetPort: {{ .Values.root_graphql.service.default.targetPort }} 
  selector:
    io.kompose.service: root-graphql
status:
  loadBalancer: {}
