apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.4.0 (c7964e7)
  creationTimestamp: null
  labels:
    io.kompose.service: api
  name: api
spec:
  replicas: {{ .Values.api.deployment.replicas }}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: api
    spec:
      containers:
      - args:
        - npm
        - run
        - api
        - --silent
        env:
        - name: BASE_QUEUE_NAME
          value: recollect
        - name: ES_INDEX
          value: recollect-events
        - name: ES_URL
          value: http://elasticsearch:{{ .Values.elasticsearch.service.default.port }}
        - name: PORT
          value: {{ .Values.api.service.default.targetPort }}
        - name: QUEUE_NAME
          value: recollect-index
        - name: RABBITMQ_URL
          value: amqp://rabbitmq
        image: {{ .Values.api.deployment.registry }}/{{ .Values.api.deployment.image }}:{{ .Values.api.deployment.tag }}
        name: api
        ports:
        - containerPort: {{ .Values.api.service.default.targetPort }}
        resources: {}
        workingDir: /usr/src/app
      restartPolicy: Always
status: {}
