apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.4.0 (c7964e7)
  creationTimestamp: null
  labels:
    io.kompose.service: elasticsearch
  name: elasticsearch
spec:
  replicas: {{ .Values.elasticsearch.deployment.replicas }}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: elasticsearch
    spec:
      containers:
      - image: {{ .Values.image.registry }}/{{ .Values.elasticsearch.deployment.image }}:{{ .Values.elasticsearch.deployment.tag }}
        name: elasticsearch
        ports:
        - containerPort: {{ .Values.elasticsearch.service.default.targetPort }}
        resources: {}
      restartPolicy: Always
status: {}
