apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.4.0 (c7964e7)
  creationTimestamp: null
  labels:
    io.kompose.service: rabbitmq
  name: rabbitmq
spec:
  replicas: {{ .Values.rabbitmq.deployment.replicas }}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: rabbitmq
    spec:
      containers:
      - image: "{{ .Values.global.image.registry }}/{{ .Values.rabbitmq.deployment.image.name }}:{{ .Values.rabbitmq.deployment.image.tag }}"
        name: rabbitmq
        ports:
        - containerPort: {{ .Values.rabbitmq.service.default.targetPort }}
        - containerPort: {{ .Values.rabbitmq.service.management.targetPort }}
        resources: {}
      restartPolicy: Always
status: {}
