apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.4.0 (c7964e7)
  creationTimestamp: null
  labels:
    io.kompose.service: rabbitmq
  name: rabbitmq
spec:
  type: ClusterIP
  ports:
  - name: "{{ .Values.rabbitmq.service.default.name }}"
    port: {{ .Values.rabbitmq.service.default.port }}                                           
    targetPort: {{ .Values.rabbitmq.service.default.targetPort }}
  - name: "{{ .Values.rabbitmq.service.management.name }}"
    port: {{ .Values.rabbitmq.service.management.port }}                                           
    targetPort: {{ .Values.rabbitmq.service.management.targetPort }}
  selector:
    io.kompose.service: rabbitmq
status:
  loadBalancer: {}
