apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.4.0 (c7964e7)
  creationTimestamp: null
  labels:
    io.kompose.service: recollect-example
  name: recollect-example
spec:
  replicas: {{ .Values.recollect_example.deployment.replicas }}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: recollect-example
    spec:
      containers:
      - args:
        - npm
        - start
        env:
        - name: RECOLLECT_API
          value: "http://api:{{ .Values.api.service.default.port }}/api/create"
        image: "{{ .Values.image.registry }}/{{ .Values.recollect_example.deployment.image.name }}:{{ .Values.recollect_example.deployment.image.tag }}"
        name: recollect-example
        ports:
        - containerPort: {{ .Values.recollect_example.service.default.targetPort }}
        resources: {}
        workingDir: /usr/src/app
      restartPolicy: Always
status: {}
