apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.4.0 (c7964e7)
  creationTimestamp: null
  labels:
    io.kompose.service: recollect-example
    #external true
  name: recollect-example
spec:
  type: ClusterIP
  ports:
  - name: "{{ .Values.recollect_example.service.default.name }}"
    port: {{ .Values.recollect_example.service.default.port }}
    targetPort: {{ .Values.recollect_example.service.default.targetPort }}
  selector:
    io.kompose.service: recollect-example
status:
  loadBalancer: {}
