apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.4.0 (c7964e7)
  creationTimestamp: null
  labels:
    io.kompose.service: root-app
  name: root-app
spec:
  type: NodePort
  ports:
  - name: "3100"
    port: 3100
    targetPort: 3100
    nodePort: 30102
  selector:
    io.kompose.service: root-app
status:
  loadBalancer: {}
