apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: "root-app-env"
data:
#  PORT: "{{ .Values.root_app.service.default.port }}"
#  MONGODB_URI: mongodb://root-db/icu
#  ELASTICSEARCH_IP: root-elastic
  MY_VALUE: "Hello World"

  
  
