apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.4.0 (c7964e7)
  creationTimestamp: null
  labels:
    io.kompose.service: root-db
  name: root-db
spec:
  replicas: {{ .Values.root_db.deployment.replicas }} 
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: root-db
    spec:
      containers:
      - image: "{{ .Values.image.registry }}/{{ .Values.root_db.deployment.image.name }}:{{ .Values.root_db.deployment.image.tag }}"
        name: root-db
        resources: {}
        
        volumeMounts:
        - name: mongo-volume
          mountPath: /data/db
          readOnly: false
      volumes:
      - name: mongo-volume
        hostPath:
          path: "/data/mongo/linnovate/root/{{ .Release.Namespace }}"

      restartPolicy: Always
status: {}
