apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.4.0 (c7964e7)
  creationTimestamp: null
  labels:
    io.kompose.service: root-elastic
  name: root-elastic
spec:
  replicas: {{ .Values.root_elastic.deployment.replicas }}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: root-elastic
    spec:
      containers:
      - image: "{{ .Values.global.image.registry }}/{{ .Values.root_elastic.deployment.image.name }}:{{ .Values.root_elastic.deployment.image.tag }}"
        name: root-elastic
        resources: {}
      restartPolicy: Always
status: {}
