apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.4.0 (c7964e7)
  creationTimestamp: null
  labels:
    io.kompose.service: root-elastic
  name: root-elastic
spec:
  clusterIP: None
  ports:
  - name: "{{ .Values.root_elastic.service.default.name }}"
    port: {{ .Values.root_elastic.service.default.port }}
    targetPort: {{ .Values.root_elastic.service.default.targetPort }}
  selector:
    io.kompose.service: root-elastic
status:
  loadBalancer: {}
