apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.4.0 (c7964e7)
  creationTimestamp: null
  labels:
    io.kompose.service: kibana
    #external true
  name: kibana
spec:
  type: ClusterIP
  ports:
  ports:
  - name: {{ .Values.kibana.service.default.name }}
    port: {{ .Values.kibana.service.default.port }}
    targetPort: {{ .Values.kibana.service.default.targetPort }}
  selector:
    io.kompose.service: kibana
status:
  loadBalancer: {}
