apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: root-app-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/proxy-body-size: 100m
spec:
  rules:
  - host: root-app.{{ .Release.Namespace }}.{{ .Values.ingress.wildcard }}
    http:
      paths:
      - path: /
        backend:
          serviceName: root-app
          servicePort: 3100
