apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.4.0 (c7964e7)
  creationTimestamp: null
  labels:
    io.kompose.service: mongo
  name: mongo
spec:
  replicas: {{ .Values.mongo.deployment.replicas }}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: mongo
    spec:
      containers:
      - image: "{{ .Values.global.image.registry }}/{{ .Values.mongo.deployment.image.name }}:{{ .Values.mongo.deployment.image.tag }}"
        name: mongo
        ports:
        - containerPort: {{ .Values.mongo.service.default.targetPort }}
        resources: {}
      restartPolicy: Always
status: {}
