apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.4.0 (c7964e7)
  creationTimestamp: null
  labels:
    io.kompose.service: mongo
  name: mongo
spec:
  ports:
  - name: "{{ .Values.mongo.service.default.name }}"
    port: {{ .Values.mongo.service.default.port }}
    targetPort: {{ .Values.mongo.service.default.targetPort }}
  selector:
    io.kompose.service: mongo
status:
  loadBalancer: {}
