apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.4.0 (c7964e7)
  creationTimestamp: null
  labels:
    io.kompose.service: reroute-ui
  name: reroute-ui
spec:
  type: NodePort
  ports:
  - name: "9000"
    port: 9000
    targetPort: 9000
    nodePort: 30101
  selector:
    io.kompose.service: reroute-ui
status:
  loadBalancer: {}
