apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.4.0 (c7964e7)
  creationTimestamp: null
  labels:
    io.kompose.service: reroute-ui
  name: reroute-ui
spec:
  type: ClusterIP
  ports:
  - name: {{ .Values.reroute-ui.service.default.name }}
    port: {{ .Values.reroute-ui.service.default.port }}
    targetPort: {{ .Values.reroute-ui.service.default.targetPort }}
  selector:
    io.kompose.service: reroute-ui
status:
  loadBalancer: {}
