apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.4.0 (c7964e7)
  creationTimestamp: null
  labels:
    io.kompose.service: reroute-api
  name: reroute-api
spec:
  replicas: {{ .Values.reroute_api.deployment.replicas }}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: reroute-api
    spec:
      containers:
      - args:
        - node
        - dist/index
        env:
        - name: DEBUG
          value: express-mongoose-es6-rest-api:*
        - name: JWT_SECRET
          value: 0a6b944d-d2fb-46fc-a85e-0295c986cd9f
        - name: MONGO_HOST
          value: mongodb://mongo/reroute-api
        - name: MONGO_PORT
          value: "{{ .Values.mongo.service.default.port }}"
        - name: NODE_ENV
          value: development
        - name: PORT
          value: "{{ .Values.reroute_api.service.default.targetPort }}"
        image: "{{ .Values.image.registry }}/{{ .Values.reroute_api.deployment.image.name }}:{{ .Values.reroute_api.deployment.image.tag }}"
        name: reroute-api
        ports:
        - containerPort: {{ .Values.reroute_api.service.default.targetPort }}
        resources: {}
        workingDir: /usr/src/app
      restartPolicy: Always
status: {}
