apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.4.0 (c7964e7)
  creationTimestamp: null
  labels:
    io.kompose.service: reroute-ui
  name: reroute-ui
spec:
  replicas: {{ .Values.reroute-ui.deployment.replicas }}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: reroute-ui
    spec:
      containers:
      - args:
        - node
        - server
        env:
        - name: PORT
          value: {{ .Values.reroute-ui.service.default.targetPort }} 
        - name: RULES_API
          value: http://reroute-api:{{ .Values.reroute-api.service.default.port }}
        image: 
        name: {{ .Values.image.registry }}/{{ .Values.reroute-ui.deployment.image }}:{{ .Values.reroute-ui.deployment.tag }}
        ports:
        - containerPort: {{ .Values.reroute-ui.service.default.targetPort }} 
        resources: {}
        workingDir: /usr/src/app
      restartPolicy: Always
status: {}
