apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.api.name }}-{{ .Values.deployenv }}-service"
  namespace: "{{ .Values.group }}-{{ .Values.deployenv }}"
  labels:
    api: "{{ .Values.api.name }}-{{ .Values.deployenv }}"
spec:
#  type: NodePort
  type: ClusterIP
  ports:
  - port: {{ .Values.api.service.default.port }}
    targetPort: {{ .Values.api.service.default.targetPort }}
  selector:
    api: "{{ .Values.api.name }}-{{ .Values.deployenv }}"
