apiVersion: v1
kind: PersistentVolume
metadata:
  name: "nfs-{{ .Values.app.name }}-{{ .Values.deployenv }}"
  namespace: "{{ .Values.group }}-{{ .Values.deployenv }}"
spec:
  capacity:
    storage: 2.5G
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.116.82.93
    # Exported path of your NFS server
    path: "/data/jdc/files/spiritual_dev"
