apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.4.0 (c7964e7)
  creationTimestamp: null
  labels:
    io.kompose.service: reroute-ui
  name: reroute-ui
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: reroute-ui
    spec:
      containers:
      - args:
        - node
        - server
        env:
        - name: PORT
          value: "9000"
        - name: RULES_API
          value: http://reroute-api:4040
        image: linnovate/reroute-ui
        name: reroute-ui
        ports:
        - containerPort: 9000
        resources: {}
        workingDir: /usr/src/app
      restartPolicy: Always
status: {}
